---
- hosts: spine1
  sudo: yes
  tasks:
  - name: Configure BGP peer
    shell: cl-bgp as 65001 neighbor  add 10.12.12.2 remote-as 65002
  - name: Add lo
    shell: cl-bgp network add 10.1.1.1/32
  - name: Add ethernet
    shell: cl-bgp network add 10.12.12.0/24
  - name: update leaf 1 timers
    shell: sudo vtysh -c "config t" -c "router bgp 65001" -c "neighbor 10.12.12.2 timers 1 3"
  - name: Save bgp config
    shell: sudo vtysh -c "write mem"

- hosts: leaf1
  sudo: yes
  tasks:
  - name: Configure BGP peer spine1
    shell: cl-bgp as 65002 neighbor add 10.12.12.1 remote-as 65001
  - name: Configure BGP peer leaf2
    shell: cl-bgp as 65002 neighbor add 10.23.23.3 remote-as 65003
  - name: Add lo
    shell: cl-bgp network add 10.2.2.2/32
  - name: Add ethernet to spine1
    shell: cl-bgp network add 10.12.12.0/24
  - name: Add ethernet to leaf2
    shell: cl-bgp network add 10.23.23.0/24
  - name: update leaf 2 timers
    shell: sudo vtysh -c "config t" -c "router bgp 65002" -c "neighbor 10.23.23.3 timers 1 3"
  - name: update spine1 timers
    shell: sudo vtysh -c "config t" -c "router bgp 65002" -c "neighbor 10.12.12.1 timers 1 3"
  - name: Save bgp config
    shell: sudo vtysh -c "write mem"

- hosts: leaf2
  sudo: yes
  tasks:
  - name: Configure BGP peer
    shell: cl-bgp as 65003 neighbor add 10.23.23.2 remote-as 65002
  - name: Add lo
    shell: cl-bgp network add 10.3.3.3/32
  - name: Add ethernet
    shell: cl-bgp network add 10.23.23.0/24
  - name: update timers
    shell: sudo vtysh -c "config t" -c "router bgp 65003" -c "neighbor 10.23.23.2 timers 1 3"
  - name: Save bgp config
    shell: sudo vtysh -c "write mem"