---
- hosts: leafs
  become: yes
  roles:
    - leaf
  handlers:
    - include: roles/leaf/handlers/main.yml
      static: yes

- hosts: spines
  become: yes
  roles:
    - spine
  handlers:
    - include: roles/spine/handlers/main.yml
      static: yes