---
- hosts: leaf1
  tasks:
  - name: download ACL Accounting
    get_url: url=https://raw.githubusercontent.com/plumbis/chinog15/master/acl_accounting.py dest=/home/cumulus/acl_accounting.py

  - name: download dynamic CoPP
    get_url: url=https://raw.githubusercontent.com/plumbis/chinog15/master/dynamic_copp.py dest=/home/cumulus/dynamic_copp.py

- hosts: leaf2
  tasks: 
   - name: download BGP neighbor capture
     get_url: url=https://raw.githubusercontent.com/plumbis/chinog15/master/bgp_neighbor_capture.py dest=/home/cumulus/bgp_neighbor_capture.py
