---
####################################
## This playbook will install Docker Engine on a Cumulus Linux Switch
## This has been tested with Docker Engine 1.12 and Cumulus Linux 3.0.0
## This playbook is provided as a best effort solution.
## Please report any issues through the GitHub issues link
##
## To run the playbook issue
##    ansible-playbook install_docker.yml -i leaf1, --ask-pass --ask-sudo-pass
##
## Where "leaf1" is the DNS hostname or IP address
## of the node to install the Docker Engine on.
##
## !!!!! The comma (,) is required !!!!!
##
## To run this directly from a Cumulus Linux switch
## First install Ansible with
##    apt-get install ansible
## then
##     ansible-playbook install_docker.yml -i localhost, --ask-pass --ask-sudo-pass
####################################

- hosts: all
  become: yes
  tasks:
  - name: Verify the minimum support Cumulus Linux Version
    fail: msg="Docker Engine is only supported on Cumulus Linux 3.0 or later"
    when: ansible_lsb.major_release|int > 3

  - name: Add Debian Apt Repo
    apt_repository:
      repo: 'deb http://ftp.us.debian.org/debian/ jessie main contrib non-free'
      state: present

  - name: Install Docker Pre-Reqs ca certs
    apt:
      name: ca-certificates

  - name: Add Apt Key for Docker
    apt_key:
      keyserver: p80.pool.sks-keyservers.net
      id: 58118E89F3A912897C070ADBF76221572C52609D

  - name: Add Docker Apt Repo
    apt_repository:
      repo: 'deb https://apt.dockerproject.org/repo debian-jessie main'
      state: present
      update_cache: yes

  - name: Install Docker
    apt: name=docker-engine

  - name: Disable Docker iptables
    lineinfile:
      dest: /etc/systemd/system/docker.service.d/noiptables.conf
      state: present
      create: yes
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    with_items:
      - { regexp: '^\[Service]', line: '[Service]'}
      - { regexp: '^ExecStart=', line: 'ExecStart='}
      - { regexp: '^ExecStart==\/usr\/bin', line: 'ExecStart=/usr/bin/docker daemon -H fd:// --iptables=false'}

  - name: Start Docker
    service: name=docker state=started
