---
####################################
## This playbook will install Windows Powershell on a Cumulus Linux Switch
## This has been tested with Powershell for Ubuntu 16.04 v6.0.0-alpha.9
## and Cumulus Linux 3.0.1.
##
## This playbook is provided as a best effort solution.
## Please report any issues through the GitHub issues link.
##
## IMPORTANT WARNING: This playbook will permanently change
## the virtual memory limit on your Cumulus Linux device. This may
## have adverse impact if a process is out of control.
##
## To run the playbook issue
##    ansible-playbook install_powershell.yml -i leaf1, --ask-pass --ask-sudo-pass
##
## Where "leaf1" is the DNS hostname or IP address
## of the node to install the Docker Engine on.
##
## !!!!! The comma (,) is required !!!!!
##
## To run this directly from a Cumulus Linux switch
## First install Ansible with
##    apt-get install ansible
## then
##     ansible-playbook install_powershell.yml -i localhost, --ask-pass --ask-sudo-pass
####################################

- hosts: all
  become: yes
  tasks:
  - name: Verify the minimum support Cumulus Linux Version
    fail: msg="Docker Engine is only supported on Cumulus Linux 3.0 or later"
    when: ansible_lsb.major_release|int > 3

 # Sid Repo is required for libicu55 powershell requirement
  - name: Add Debian Sid Apt Repo
    apt_repository:
      repo: 'deb http://ftp.us.debian.org/debian/ sid main contrib non-free'
      state: present
      update_cache: yes

  # The libstdc++6 package must be pinned to the Sid repo to pull the correct version.
  # A blank mark is required due to how Ansible handles apt pinning
  - name: Apt pin libstdc++
    blockinfile:
      dest: /etc/apt/preferences.d/30_powershell_sid
      block: |
        Package: libstdc++6
        Pin: release n=sid
        Pin-Priority: 999
      create: yes
      marker: ""

  - name: Add Debian Jessie Apt Repo
    apt_repository:
      repo: 'deb http://ftp.us.debian.org/debian/ jessie main contrib non-free'
      state: present
      update_cache: yes

  - name: Install Powershell prereq libundwind8
    apt:
      name: libunwind8

  - name: Install Powershell preq libicu55
    apt:
      name: libicu55

  - name: Download Powershell Ubuntu 16.04 package
    get_url:
        url: https://github.com/PowerShell/PowerShell/releases/download/v6.0.0-alpha.9/powershell_6.0.0-alpha.9-1ubuntu1.16.04.1_amd64.deb
        dest: /tmp/powershell.deb

  # SECOND WARNING
  # This will permanently change the amount of virtual memory
  # a process may consume. Please use caution.
  - name: Increase virtual memory limit
    replace:
      dest: /etc/security/limits.d/99-cumulus.conf
      regexp: '^1\:  soft  as        1048576'
      replace: '^1\:  soft  as        unlimited'

  - name: Install Powershell
    apt:
      deb: /tmp/powershell.deb

