---
- hosts: spine1
  sudo: yes
  tasks:
  - name: spine1-leaf1
    cl_interface: name=swp49 ipv4=10.12.12.1/24
  - name: loopback
    cl_interface: name=lo ipv4=10.1.1.1/32
  - name: Apply changes
    command: ifreload -a

- hosts: leaf1
  sudo: yes
  tasks:
  - name: spine1-leaf1
    cl_interface: name=swp1s0 ipv4=10.12.12.2/24
  - name: loopback
    cl_interface: name=lo ipv4=10.2.2.2/32
  - name: leaf1-leaf2
    cl_interface: name=swp17 ipv4=10.23.23.2/24
  - name: Apply changes
    command: ifreload -a

- hosts: leaf2
  sudo: yes
  tasks:
  - name: lo
    cl_interface: name=lo ipv4=10.3.3.3/32
  - name: leaf2-leaf1
    cl_interface: name=swp17 ipv4=10.23.23.3/24
  - name: Apply changes
    command: ifreload -a