---
- hosts: spine1
  sudo: yes
  tasks:
  - name: spine1-leaf1
    cl_interface: name=swp49 
  - name: spine1-leaf1-2
    cl_interface: name=swp50
  - name: spine1-spine2
    cl_interface: name=swp17
  - name: spine1-spine2-2
    cl_interface: name=swp18
  - name: spine1-leaf2
    cl_interface: name=swp51
  - name: spine1-leaf2-1
    cl_interface: name=swp52
  - name: loopback
    cl_interface: name=lo ipv4=10.1.1.1/32
  - name: Apply changes
    command: ifreload -a

- hosts: leaf1
  sudo: yes
  tasks:
  - name: loopback
    cl_interface: name=lo ipv4=10.2.2.2/32
  - name: leaf1-leaf2
    cl_interface: name=swp17
  - name: leaf1-leaf2-2
    cl_interface: name=swp18
  - name: leaf1-spine1
    cl_interface: name=swp1s0
  - name: leaf1-spine1-2
    cl_interface: name=swp1s1
  - name: leaf1-spine2
    cl_interface: name=swp1s2
  - name: leaf1-spine2-2
    cl_interface: name=swp1s3
  - name: Apply changes
    command: ifreload -a

- hosts: leaf2
  sudo: yes
  tasks:
  - name: lo
    cl_interface: name=lo ipv4=10.4.4.4/32
  - name: leaf2-leaf1
    cl_interface: name=swp17
  - name: leaf2-leaf1-2
    cl_interface: name=swp18
  - name: leaf2-spine2
    cl_interface: name=swp1s0
  - name: leaf2-spine2-2
    cl_interface: name=swp1s1
  - name: leaf2-spine1
    cl_interface: name=swp1s2
  - name: leaf2-spine1-2
    cl_interface: name=swp1s3
  - name: Apply changes
    command: ifreload -a

- hosts: spine2
  sudo: yes
  tasks:
  - name: lo
    cl_interface: name=lo ipv4=10.2.2.2/32
  - name: spine2-leaf2
    cl_interface: name=swp49 
  - name: spine2-leaf2-2
    cl_interface: name=swp50
  - name: spine2-spine1
    cl_interface: name=swp17
  - name: spine2-spine1-2
    cl_interface: name=swp18
  - name: spine2-leaf1
    cl_interface: name=swp51
  - name: spine2-leaf1-1
    cl_interface: name=swp52
  - name: Apply changes
    command: ifreload -a