---
- hosts: me
  become: yes
  roles:
    - workbench
  handlers:
    - include: handlers/main.yml

- hosts: leafs
  become: yes
  tasks:
    - include: roles/leaf/tasks/reprovision.yml
  handlers:
    - include: handlers/main.yml

- hosts: spines
  become: yes
  tasks:
    - include: roles/spine/tasks/reprovision.yml
  handlers:
    - include: handlers/main.yml