---
- hosts: network
  sudo: yes
  tasks:
  - name: Enable BGP
    cl_quagga_protocol: name="bgpd" state="present"
    notify:
    - restart quagga

  handlers:
   - name: restart quagga
     service: name=quagga state=restarted