---
- name: restart isc-dhcp-server
  service: name=isc-dhcp-server state=restarted

- name: restart quagga
  service: name=quagga state=restarted

- name: reload networking
  service: name=networking state=reloaded

- name: reload quagga
  service: name=quagga state=reloaded