---
- name: Install License
  cl_license: src="http://192.168.0.1/{{ansible_hostname}}.lic"
  notify: restart switchd

- name: Copy Quagga daemons file
  copy: src=daemons dest=/etc/quagga/daemons backup=yes
  notify: restart quagga

- name: Enable Quagga Reload
  copy: src=quagga dest=/etc/default/quagga
  notify: restart quagga

- meta: flush_handlers

- name: Disable AAAA DNS lookups
  replace:
    dest=/etc/gai.conf
    regexp="#precedence ::ffff:0:0/96  10"
    replace="precedence ::ffff:0:0/96  100"

- name: Copy /etc/network/interfaces
  template: src=interfaces.j2 dest=/etc/network/interfaces
  notify: reload networking

- name: Copy Quagga Configuration
  template: src=quagga.conf.j2 dest=/etc/quagga/Quagga.conf
  notify: reload quagga
