---
- hosts: spine1
  sudo: yes
  tasks:
  - name: Configure BGP ASN
    command: "{{item}}"
    with_items:
      - cl-bgp as 65111 router-id set 10.11.11.11
      - cl-bgp peer-group add fabric
      - cl-bgp maximum-paths set 16
      - cl-bgp network add 10.11.11.11/32
      - cl-bgp bestpath set as-path multipath-relax
      - cl-bgp neighbor add fabric remote-as external
      - cl-bgp timers set connect 1 neighbor fabric
      - cl-bgp timers set keepalive 1 holdtime 3 neighbor fabric
      - cl-bgp advertisement-interval set 0 neighbor fabric
      - cl-bgp capability set extended-nexthop neighbor fabric
      
  - name: Configure BGP Fabric Settings
    command: "{{ item[0] | replace('%iface%', item[1]) }}"
    with_nested: 
      - ["cl-bgp interface add %iface%",
         "cl-rctl interface clear %iface% ipv6 nd suppress-ra",
         "cl-rctl interface set %iface% ipv6 nd ra-interval 5",
         "cl-bgp neighbor add %iface% peer-group fabric",
         "cl-rctl write-config integrated",
        ]
      - ["swp17", "swp18", "swp49", "swp50", "swp51", "swp52"]
      
- hosts: spine2
  sudo: yes
  tasks:
  - name: Configure BGP ASN
    command: "{{item}}"
    with_items:
      - cl-bgp as 65222 router-id set 10.22.22.22
      - cl-bgp peer-group add fabric
      - cl-bgp maximum-paths set 16
      - cl-bgp network add 10.22.22.22/32
      - cl-bgp bestpath set as-path multipath-relax
      - cl-bgp neighbor add fabric remote-as external
      - cl-bgp timers set connect 1 neighbor fabric
      - cl-bgp timers set keepalive 1 holdtime 3 neighbor fabric
      - cl-bgp advertisement-interval set 0 neighbor fabric
      - cl-bgp capability set extended-nexthop neighbor fabric

  - name: Configure BGP Fabric Settings
    command: "{{ item[0] | replace('%iface%', item[1]) }}"
    with_nested: 
      - ["cl-bgp interface add %iface%",
         "cl-rctl interface clear %iface% ipv6 nd suppress-ra",
         "cl-rctl interface set %iface% ipv6 nd ra-interval 5",
         "cl-bgp neighbor add %iface% peer-group fabric",
         "cl-rctl write-config integrated",
        ]
      - ["swp17", "swp18", "swp49", "swp50", "swp51", "swp52"]
      
- hosts: leaf1
  sudo: yes
  tasks:
  - name: Configure BGP ASN
    command: "{{item}}"
    with_items:
      - cl-bgp as 65001 router-id set 10.1.1.1
      - cl-bgp peer-group add fabric
      - cl-bgp maximum-paths set 16
      - cl-bgp network add 10.1.1.1/32
      - cl-bgp bestpath set as-path multipath-relax
      - cl-bgp neighbor add fabric remote-as external
      - cl-bgp timers set connect 1 neighbor fabric
      - cl-bgp timers set keepalive 1 holdtime 3 neighbor fabric
      - cl-bgp advertisement-interval set 0 neighbor fabric
      - cl-bgp capability set extended-nexthop neighbor fabric
            
  - name: Configure BGP Fabric Settings
    command: "{{ item[0] | replace('%iface%', item[1]) }}"
    with_nested: 
      - ["cl-bgp interface add %iface%",
         "cl-rctl interface clear %iface% ipv6 nd suppress-ra",
         "cl-rctl interface set %iface% ipv6 nd ra-interval 5",
         "cl-bgp neighbor add %iface% peer-group fabric",
         "cl-rctl write-config integrated",
        ]
      - ["swp17", "swp18", "swp1s0", "swp1s1", "swp1s2", "swp1s3"]
      
- hosts: leaf2
  sudo: yes
  tasks:
  - name: Configure BGP ASN
    command: "{{item}}"
    with_items:
      - cl-bgp as 65002 router-id set 10.2.2.2
      - cl-bgp peer-group add fabric
      - cl-bgp maximum-paths set 16
      - cl-bgp network add 10.2.2.2/32
      - cl-bgp bestpath set as-path multipath-relax
      - cl-bgp neighbor add fabric remote-as external
      - cl-bgp timers set connect 1 neighbor fabric
      - cl-bgp timers set keepalive 1 holdtime 3 neighbor fabric
      - cl-bgp advertisement-interval set 0 neighbor fabric
      - cl-bgp capability set extended-nexthop neighbor fabric
      
  - name: Configure BGP Fabric Settings
    command: "{{ item[0] | replace('%iface%', item[1]) }}"
    with_nested: 
      - ["cl-bgp interface add %iface%",
         "cl-rctl interface clear %iface% ipv6 nd suppress-ra",
         "cl-rctl interface set %iface% ipv6 nd ra-interval 5",
         "cl-bgp neighbor add %iface% peer-group fabric",
         "cl-rctl write-config integrated",
        ]
      - ["swp17", "swp18", "swp1s0", "swp1s1", "swp1s2", "swp1s3"]
