---
- hosts: network
  sudo: yes
  tasks:
  - name: Enable bgpd and zebra
    replace: dest=/etc/quagga/daemons regexp='(bgpd|zebra|ospfd)=no' replace='\1=yes' backup=yes
    notify: restart quagga

  handlers:
   - name: restart quagga
     service: name=quagga state=restarted
